version: 2.1
jobs:
  build_docker:
    machine: true
      #- image: cimg/base:2020.01
        #auth:
          #username: mydockerhub-user
          #password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" $DOCKER_USER
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t yupi/nginx .
      - run: docker push yupi/nginx

workflows:
  my_flow:
    jobs:
      - build_docker:
          context: DockerHub
