version: 2.1
jobs:
  build_docker:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t yupi/nginx .
      - run: docker push yupi/nginx

  deploy_aws:
    machine: true
    steps:
      - checkout
      - run:
        name: install sshpass
        command: |
          sudo apt update
          sudo -y apt-get install sshpass
#      - run: sshpass -p $ssh_passwd ssh circle-ci@ec2-18-223-143-183.us-east-2.compute.amazonaws.com
workflows:
  my_flow:
    jobs:
      - build_docker:
          context: DockerHub
      - deploy_aws:
          requires:
            - build_docker
          context: AWS

# AllowUsers circle-ci
# PasswordAuthentication yes
