version: 2.1
jobs:
  build_docker:
    docker:
      - image: alpine:3.7
        #auth:
          #username: mydockerhub-user
          #password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ls -lah
workflows:
  my_flow:
    jobs:
      - build_docker
