version: 2.1
jobs:
  build_docker:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t yupi/nginx .
      - run: docker push yupi/nginx

  deploy_aws:
    machine: true
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get -yq install sshpass
      - run: sshpass -p $ssh_passwd ssh circle-ci@ec2-18-222-172-174.us-east-2.compute.amazonaws.com 'docker pull yupi/nginx; docker run --rm --name nginx -p 80:80 -p1280:1280 -d yupi/nginx'
workflows:
  install_nginx_on_AWS:
    jobs:
      - build_docker:
          context: DockerHub
      - deploy_aws:
          requires:
            - build_docker
          context: AWS

# AllowUsers circle-ci
# PasswordAuthentication yes
