version: 2.1
jobs:
  build_docker:
    docker:
      - image: cimg/base:2020.01
        #auth:
          #username: mydockerhub-user
          #password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ls -lah
      - run: docker build -t yupi/nginx:0.0.1 .

workflows:
  my_flow:
    jobs:
      - build_docker
